apiVersion: v1
kind: Service
metadata:
  name: new
spec:
  type: LoadBalancer
  selector:
    app: new
  ports:
  - port: 3333
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: new
        image: keeprich/k8s-web-connect-to-ngnix:2.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000    